/**
    This file is autogenerated using the command `yarn app-store:build --watch`.
    Don't modify this file manually.
**/
export const REDIRECT_APPS = [
  "amie",
  "autocheckin",
  "baa-for-hipaa",
  "bolna",
  "caretta",
  "chatbase",
  "clic",
  "cron",
  "deel",
  "elevenlabs",
  "fonio-ai",
  "framer",
  "granola",
  "greetmate-ai",
  "lindy",
  "linear",
  "millis-ai",
  "monobot",
  "n8n",
  "pipedream",
  "raycast",
  "retell-ai",
  "vimcal",
  "synthflow",
  "telli",
<<<<<<< HEAD
  "link-as-an-app",
  "vimcal",
=======
>>>>>>> 89c3b809de522a5025339b78a8ba7bb527cd77d5
  "wordpress",
  "zapier",
] as const;
export type RedirectApp = (typeof REDIRECT_APPS)[number];
